version: "3.8"

services:
  # Spring Boot Service
  inventory-service:
    build:
      context: ./  # Root directory containing the Dockerfile
      dockerfile: Dockerfile  # Use the custom Dockerfile to build the Spring Boot app
    container_name: inventory-ms
    ports:
      - "8080:8080"  # Expose Spring Boot app on port 8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/zaggle_development
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres # Ensure Spring Boot starts after the database service is available

  # PostgreSQL Service
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: zaggle_development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
